GET https://vob939902b.execute-api.us-east-2.amazonaws.com/prod/spaces
###

POST  https://vob939902b.execute-api.us-east-2.amazonaws.com/prod/spaces
content-type: application/json

    {
        "location": "Paris"
    }
###


GET https://vob939902b.execute-api.us-east-2.amazonaws.com/prod/spaces?id=26a38b79-5587-4a2c-8484-6e2f551442d0
###

DELETE https://vob939902b.execute-api.us-east-2.amazonaws.com/prod/spaces?id=26a38b79-5587-4a2c-8484-6e2f551442d0
###

PUT   https://vob939902b.execute-api.us-east-2.amazonaws.com/prod/spaces?id=26a38b79-5587-4a2c-8484-6e2f551442d0
content-type: application/json

    {
        "location": "Paris2"
    }
###